A brief description of the major design decisions in this data
structure.

* SmartPointer (external library)
  A pointer which counts references and automatically deallocated the
  pointed-to object when the reference count drops to 0.

* TimeStampedArray (TSA)
  A simple array class with an associated time stamp.

* ListNode
  Decided to keep ListNodes templated, since it makes deallocation
  simple.  Nodes storing a void pointer can't directly delete the
  memory, since deletion of a void pointer is undefined.
  
** next
   A vector of TSAs of SmartPointers to ListNodes, one for each time
   at which the next node in the list changes.

* PersistentSkipList

** head
   A map of dummy head nodes which contain no data, but are guaranteed
   to precede every other node in the skip list.

** tail
   Same as the above head map, but which are dummy nodes guaranteed to
   follow every other node in the skip list.

** data_set
   The set of all points in the data.  This prevents duplicates, but
   adds O(logn) time complexity of overhead to insertion.
